# Generated by Django 5.2.5 on 2025-09-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computergroup',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='computergroup',
            name='divider',
            field=models.CharField(blank=True, choices=[('', 'None'), (' ', '(Space)'), ('-', '-')], default='', max_length=1, verbose_name='Name Devider'),
        ),
        migrations.AlterField(
            model_name='computergroup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Computer Group Name'),
        ),
    ]